/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QRouteImport } from './routes/q'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QChar123userChar125Char123CollectionChar125RouteImport } from './routes/q.{$user}.{-$collection}'

const QRoute = QRouteImport.update({
  id: '/q',
  path: '/q',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QChar123userChar125Char123CollectionChar125Route =
  QChar123userChar125Char123CollectionChar125RouteImport.update({
    id: '/{$user}/{-$collection}',
    path: '/{$user}/{-$collection}',
    getParentRoute: () => QRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/q': typeof QRouteWithChildren
  '/q/{$user}/{-$collection}': typeof QChar123userChar125Char123CollectionChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/q': typeof QRouteWithChildren
  '/q/{$user}/{-$collection}': typeof QChar123userChar125Char123CollectionChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRoute
  '/q': typeof QRouteWithChildren
  '/q/{$user}/{-$collection}': typeof QChar123userChar125Char123CollectionChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/q' | '/q/{$user}/{-$collection}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/q' | '/q/{$user}/{-$collection}'
  id: '__root__' | '/' | '/_authed' | '/q' | '/q/{$user}/{-$collection}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRoute
  QRoute: typeof QRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/q': {
      id: '/q'
      path: '/q'
      fullPath: '/q'
      preLoaderRoute: typeof QRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/{$user}/{-$collection}': {
      id: '/q/{$user}/{-$collection}'
      path: '/{$user}/{-$collection}'
      fullPath: '/q/{$user}/{-$collection}'
      preLoaderRoute: typeof QChar123userChar125Char123CollectionChar125RouteImport
      parentRoute: typeof QRoute
    }
  }
}

interface QRouteChildren {
  QChar123userChar125Char123CollectionChar125Route: typeof QChar123userChar125Char123CollectionChar125Route
}

const QRouteChildren: QRouteChildren = {
  QChar123userChar125Char123CollectionChar125Route:
    QChar123userChar125Char123CollectionChar125Route,
}

const QRouteWithChildren = QRoute._addFileChildren(QRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRoute,
  QRoute: QRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
